DROP TABLE IF EXISTS products, styles, photos, skus, related, features, cart CASCADE;

CREATE TABLE IF NOT EXISTS products (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name            text,
  slogan          text,
  description     text,
  category        text,
  default_price   int
);

COPY products
FROM '/home/blin/project-sdc/p_service/files/product.csv'
WITH (FORMAT csv, HEADER true);

CREATE TABLE IF NOT EXISTS styles (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id      int references products(id),
  name            text,
  sale_price      int,
  original_price  int,
  default_style   boolean
);

COPY styles
FROM '/home/blin/project-sdc/p_service/files/styles.csv'
WITH (FORMAT csv, HEADER true, NULL 'null');

CREATE TABLE IF NOT EXISTS photos (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  style_id        int references styles(id),
  url             text,
  thumbnail_url   text
);

COPY photos
FROM '/home/blin/project-sdc/p_service/files/photos.csv'
WITH (FORMAT csv, HEADER true);

CREATE TABLE IF NOT EXISTS skus (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  style_id        int references styles(id),
  size            text,
  quantity        smallint
);

COPY skus
FROM '/home/blin/project-sdc/p_service/files/skus.csv'
WITH (FORMAT csv, HEADER true);

CREATE TABLE IF NOT EXISTS related (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product1_id     int references products(id),
  product2_id     int references products(id)
);

COPY related
FROM '/home/blin/project-sdc/p_service/files/related.csv'
WITH (FORMAT csv, HEADER true, NULL 0);

CREATE TABLE IF NOT EXISTS features (
  id              int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id      int references products(id),
  feature         text,
  value           text
);

COPY features
FROM '/home/blin/project-sdc/p_service/files/features.csv'
WITH (FORMAT csv, HEADER true, NULL 'null');

CREATE TABLE IF NOT EXISTS cart (
  id              smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_session    smallint,
  product_id      int references products(id),
  active          boolean
);

COPY cart
FROM '/home/blin/project-sdc/p_service/files/cart.csv'
WITH (FORMAT csv, HEADER true);
